// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDiem.Infrastructure.Data;

#nullable disable

namespace QLDiem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(QLDiemDbContext))]
    [Migration("20260923022708_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTro_Claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaiKhoan_Claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("TaiKhoan_Login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TaiKhoan_VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TaiKhoan_Token", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.DanhGiaNhanXet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("HocSinhId")
                        .HasColumnType("int");

                    b.Property<int>("KetQua")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungNhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NamHocId");

                    b.HasIndex("HocSinhId", "MonHocId", "NamHocId", "HocKy")
                        .IsUnique()
                        .HasDatabaseName("UX_DanhGiaNhanXet");

                    b.ToTable("DanhGiaNhanXet", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("GiaTri")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("HocSinhId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDiem")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NamHocId");

                    b.HasIndex("HocSinhId", "MonHocId", "NamHocId", "HocKy", "LoaiDiem", "ThuTu")
                        .IsUnique()
                        .HasDatabaseName("UX_Diem_DauDiem");

                    b.ToTable("Diem", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DangCongTac")
                        .HasColumnType("bit");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaGiaoVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaGiaoVien")
                        .IsUnique();

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.HocSinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoc")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DienThoaiPhuHuynh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenPhuHuynh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<string>("MaHocSinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HoTen");

                    b.HasIndex("LopId");

                    b.HasIndex("MaHocSinh")
                        .IsUnique();

                    b.ToTable("HocSinh", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.KetQuaHocKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhHieu")
                        .HasColumnType("int");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("HocSinhId")
                        .HasColumnType("int");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTongKet")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetCuaGVCN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoMonTinhDiem")
                        .HasColumnType("int");

                    b.Property<int>("XepLoaiHocTap")
                        .HasColumnType("int");

                    b.Property<int>("XepLoaiRenLuyen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NamHocId");

                    b.HasIndex("HocSinhId", "NamHocId", "HocKy")
                        .IsUnique()
                        .HasDatabaseName("UX_KetQuaHocKy");

                    b.ToTable("KetQuaHocKy", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GiaoVienChuNhiemId")
                        .HasColumnType("int");

                    b.Property<int>("Khoi")
                        .HasColumnType("int");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienChuNhiemId");

                    b.HasIndex("NamHocId");

                    b.HasIndex("Ten", "NamHocId")
                        .IsUnique();

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTietNam")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMon")
                        .IsUnique();

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.NamHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("NamHoc", (string)null);
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.PhanCongGiangDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NamHocId");

                    b.HasIndex("LopId", "MonHocId", "NamHocId")
                        .IsUnique();

                    b.ToTable("PhanCongGiangDay", (string)null);
                });

            modelBuilder.Entity("QLDiem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HocSinhId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QLDiem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QLDiem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDiem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QLDiem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.DanhGiaNhanXet", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.HocSinh", "HocSinh")
                        .WithMany("DanhSachNhanXet")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.Diem", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.HocSinh", "HocSinh")
                        .WithMany("DanhSachDiem")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.HocSinh", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.Lop", "Lop")
                        .WithMany("HocSinhs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.KetQuaHocKy", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.Lop", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.GiaoVien", "GiaoVienChuNhiem")
                        .WithMany("LopChuNhiem")
                        .HasForeignKey("GiaoVienChuNhiemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLDiem.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany("DanhSachLop")
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVienChuNhiem");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.PhanCongGiangDay", b =>
                {
                    b.HasOne("QLDiem.Domain.Entities.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.Lop", "Lop")
                        .WithMany("PhanCongs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDiem.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.GiaoVien", b =>
                {
                    b.Navigation("LopChuNhiem");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.HocSinh", b =>
                {
                    b.Navigation("DanhSachDiem");

                    b.Navigation("DanhSachNhanXet");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.Lop", b =>
                {
                    b.Navigation("HocSinhs");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.MonHoc", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QLDiem.Domain.Entities.NamHoc", b =>
                {
                    b.Navigation("DanhSachLop");
                });
#pragma warning restore 612, 618
        }
    }
}
